spring:
  profiles:
    active: dev
  application:
    name: ai-roleplay

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ai_roleplay}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345678}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# 七牛云AI配置
qiniu:
  ai:
    # 请在此处填入您的API密钥
    api-key: sk-1649a402ca3c7e9a8dd14158ae45fe8d33d9f5a37380ad2afc0809175846f603
    # 可选配置
    default-model: deepseek-v3
    timeout: 60  # 增加超时时间到60秒，避免ASR请求超时
    max-retries: 2  # 减少重试次数，避免过多重试
    asr:
      model: asr
      timeout: 60  # ASR专用超时配置
    tts:
      model: tts-1
      voice: alloy
      timeout: 30
  # 七牛云对象存储配置
  kodo:
    access-key: ${QINIU_ACCESS_KEY:L16boMfLHL7lkh15huJ5MDc08vydJ0s5oj35xG_x}
    secret-key: ${QINIU_SECRET_KEY:jrNAFPTjDGHu4dpf8aaq1ZdKHZGaXKWki7U9eqrb}
    bucket: ${QINIU_BUCKET:ai-roleplay-audio}
    domain: ${QINIU_DOMAIN:t34w0mr3r.hd-bkt.clouddn.com}  # 七牛云CDN域名，用于生成公网访问URL


# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hzau.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置
jwt:
  secret: ${JWT_SECRET:YWktcm9sZXBsYXktc3VwZXItc2VjcmV0LWp3dC1rZXktMjAyNC0xNzU4NTQ0NjUxCg==}
  expiration: 86400000  # 24小时
  refresh-expiration: 604800000  # 7天


# 服务器配置
server:
  port: 8080

# 日志配置
logging:
  level:
    com.hzau: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/ai-roleplay.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      total-size-cap: 1GB
      max-history: 30


# 文件上传配置
file:
  upload:
    base-path: E:\Code\AI-roleplay\data
    base-url: http://122.205.70.147


# SpringDoc OpenAPI配置
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# 应用信息
info:
  app:
    name: AI角色扮演网站
    description: 基于AI的角色扮演聊天平台
    version: 1.0.0